export enum TypographyVariant {
    large = 'large',
    h1 = 'h1',
    h2 = 'h2',
    h3 = 'h3',
    regular_text_16 = 'regular_text_16',
    bold_text_16 = 'bold_text_16',
    regular_text_14 = 'regular_text_14',
    medium_text_14 = 'medium_text_14',
    bold_text_14 = 'bold_text_14',
    small_text = 'small_text',
    semibold_small_text = 'semibold_small_text',
    regular_link = 'regular_link',
    small_link = 'small_link',
}